import pdb
import sys

#take the input file name , and output generated by the model-file

inp_file = open(sys.argv[1],"r")
model_file_out = open(sys.argv[2],"r")

inp_file_lines = inp_file.readlines()
model_file_out_lines = model_file_out.readlines()

#dump the contents into the file  
result = open(sys.argv[3],"w")

if len(inp_file_lines)!=len(model_file_out_lines):
	print "damn!!! number of lines incorrect... (error!!!)"
	exit(1)


#take one word from input one append it with label into final result
for i in range(len(inp_file_lines)):
    item1 = inp_file_lines[i].strip()
    item2 = model_file_out_lines[i].strip()
    result_str = item1+" "+item2+"\n"
    result.write(result_str)


inp_file.close()
model_file_out.close()
result.close()

